/**
 * The files `vertekum init` writes into a consuming repo. They are TypeScript string constants
 * rather than files on disk: packages publish raw source, so a template *file* would depend on the
 * `files` allowlist and on path resolution from inside `node_modules`. Strings sidestep both.
 */

/** The consumer config. Deliberately minimal — one collection; validation is core builtins. */
export const CONFIG_TEMPLATE = `import { defineConfig } from '@vertekum/core';

/**
 * This file's location is the working directory: the token collection, the system-governed
 * \`.vertekum/\` dir, and export output all resolve relative to it.
 *
 * \`vertekum check\` works as-is: reference, resolver, and target validation are core builtins.
 * Output formats are extensions, and export targets are root config — e.g. with
 * \`@vertekum/ext-export-terrazzo\` (and a terrazzo plugin) installed:
 *
 *   extensions: [terrazzoExportExtension],
 *   targets: [
 *     { id: 'web', exporter: 'terrazzo', composition: 'default', out: 'build',
 *       options: { plugins: [css()] } },
 *   ],
 */
export default defineConfig({
  collection: './tokens',
});
`;

/** A seed DTCG set: enough for `check` and `build` to do real work, small enough to delete. */
export const SEED_SET = `${JSON.stringify(
  {
    color: {
      $type: 'color',
      base: { $value: '#1a1a1a' },
      surface: { $value: '{color.base}' },
    },
  },
  null,
  2,
)}\n`;

/** A resolver naming the seed set. No modifiers — compositions are added by hand. */
export const SEED_RESOLVER = `${JSON.stringify(
  {
    version: '2025.10',
    name: 'default',
    sets: { core: { sources: [{ $ref: 'core.json' }] } },
    modifiers: {},
    resolutionOrder: [{ $ref: '#/sets/core' }],
  },
  null,
  2,
)}\n`;

/**
 * The stamp marks a skill as generated: `init --skill` overwrites stamped files and leaves edited
 * (stampless) ones alone, so removing the line is how a consumer takes ownership of their copy.
 */
export const SKILL_STAMP =
  '<!-- generated by vertekum init; edit freely — remove this line to keep your edits safe from `init --skill` refresh -->';

/**
 * The agent skills. They teach the CONTRACT; `vertekum describe --json` supplies the FACTS.
 * Anything enumerable at runtime — exporters, target options, the exact command list — is
 * deliberately absent: duplicating `describe` here would be stale the day after this file ships,
 * which is the failure mode that matters once Vertekum is installed in repos we do not control.
 * What IS here is semantics an agent cannot derive from `describe`: which changes go through
 * verbs, what a vocabulary refusal means, how values are stored, what the exit codes promise.
 *
 * Written as joined lines because the content contains fenced code blocks; a template literal
 * would need every backtick escaped.
 */
export const SKILL_TEMPLATE = [
  '---',
  'name: vertekum-tokens',
  'description: Use when creating, editing, or reviewing design tokens in a repo managed by Vertekum',
  '---',
  '',
  SKILL_STAMP,
  '',
  '# Working with Vertekum tokens',
  '',
  'Vertekum manages DTCG design tokens. **The files are the API.** You author token JSON directly',
  'with your normal editing tools; Vertekum resolves, validates, and builds output from them.',
  '',
  '## Orient yourself first',
  '',
  '```bash',
  'npx vertekum describe --json',
  '```',
  '',
  'This is the source of truth for what exists *here*: token sets, compositions, installed',
  'extensions, available exporters and their options, and every command you can run. Read it before',
  'assuming anything — never rely on a remembered list of exporters or commands.',
  '',
  '## The loop',
  '',
  '1. **Edit** token JSON under the collection directory (`describe` reports its path).',
  '2. **Check** — `npx vertekum check --json`. This is your compiler. It reports dangling aliases,',
  '   invalid compositions, vocabulary violations, and misconfigured export targets.',
  '3. **Build** — `npx vertekum build`. Writes the configured output targets.',
  '4. **Report** only after check passes with zero errors.',
  '',
  'Every command exits `0` when clean, `1` when the **tokens** are wrong (diagnostics — fix the',
  'tokens), and `2` when the **invocation** is wrong (fix your command, not the tokens).',
  '',
  '## Structural changes go through verbs',
  '',
  'Editing a value in place is a file edit. Anything **structural** — creating, deleting, moving,',
  'or renaming — goes through a verb, because verbs rewrite every reference and refuse to create a',
  'violation `check` would then report:',
  '',
  '```bash',
  'npx vertekum token add <path> [value]     # also: token set, token remove, token move',
  'npx vertekum token rename <from> <to>',
  'npx vertekum group add <path>             # also: group set, group remove',
  'npx vertekum set add <name>               # a set is a FILE; also: set remove',
  '```',
  '',
  '- **Never rename by editing text.** `token rename` rewrites every reference; a hand-edited path',
  '  leaves dangling aliases that you will then have to undo.',
  '- **Renaming a whole group** needs `--allow-group`. That flag is a confirmation, not a',
  '  formality: it moves every token beneath the path.',
  '- **`--dry-run`** works on every mutating command, and `--json` reports what changed. Use',
  '  `--dry-run` whenever you are unsure what a change touches.',
  '',
  '## The vocabulary says what you may not do',
  '',
  'A project may bind **schemas** to its token files (`describe` lists the bindings). A schema is a',
  'vocabulary: it fixes which names may exist, and `check` reports a name outside it like any other',
  'error. A refused name is a **stop-and-ask moment, not a workaround moment** — the vocabulary is',
  'a design decision. Schemas are ordinary files; to change a packaged one, take ownership first:',
  '`npx vertekum schema eject <source> [dest]`, then edit the copy.',
  '',
  '## How values are stored',
  '',
  'Token values are stored in DTCG 2025.10 **object notation** (a color is `colorSpace` +',
  '`components`, not a hex string). Match the notation already used in the collection — never mix a',
  'second notation into it. If a collection still holds legacy string values,',
  '`npx vertekum migrate values` converts them wholesale (`--dry-run` first).',
  '',
  '## Rules',
  '',
  '- **Never hand-edit build output.** It is generated. Change the tokens and rebuild.',
  '- **Commit build output** along with the token change. The generated diff is what a human',
  '  reviews, and it is where the consequences of a token change become visible.',
  '- A reference looks like `{color.base}`. It must resolve to a token that exists in the same',
  '  composition.',
  '',
  '## When you are stuck',
  '',
  '`check` failing with something you do not understand is a signal to stop and ask, not to try',
  'variations. Token structure is a design decision, and a human owns it.',
  '',
].join('\n');

/**
 * The release-workflow skill. Applies when the project configures the release extension; written
 * unconditionally because `init` runs before a project exists — the skill states its own scope.
 */
export const RELEASE_SKILL_TEMPLATE = [
  '---',
  'name: vertekum-release',
  'description: Use when releasing, versioning, or writing a changelog for Vertekum-managed design tokens',
  '---',
  '',
  SKILL_STAMP,
  '',
  '# Releasing Vertekum tokens',
  '',
  'This workflow applies when the project configures the release extension — `npx vertekum',
  'describe --json` shows it. Without it, stop: this repo has no token release process to run.',
  '',
  '## Preconditions',
  '',
  'A release describes a **finished** state: `npx vertekum check --json` must pass with zero',
  'errors, and build output must be current and committed, before any release step.',
  '',
  '## Severity is derived from the diff, not chosen',
  '',
  'The release engine classifies every change against the last released baseline:',
  '',
  '| change | severity |',
  '| --- | --- |',
  '| token removed, renamed, or retyped | `major` |',
  '| token added | `minor` |',
  '| value changed | `patch` |',
  '',
  'The release severity is the **highest** classification in the diff. Use this vocabulary when',
  'describing the impact of a token change — "this pass renames two tokens, so the token release',
  'is major" — and let the engine compute it rather than asserting it.',
  '',
  '## The changelog is part of the release',
  '',
  'The engine writes release notes from the classified diff. Do not hand-author changelog entries',
  'for token changes the engine already describes; add prose only for context the diff cannot',
  'carry (why, migrations, deprecation guidance).',
  '',
  '## Token severity is not the package bump',
  '',
  'The token release and the **package** that ships the tokens are different contracts. The host',
  'repository may version its package by rules that rank the same change differently — a value',
  'change can be a `patch` token release yet a `minor` package bump because it is visible in every',
  'consuming product. **Read the repository’s own contribution docs for its bump policy and',
  'follow them; never assume the two contracts align.** When the repo gives no policy, propose the',
  'token severity as the package bump and say you did so.',
  '',
  '## When you are stuck',
  '',
  'A release is an outward-facing, hard-to-reverse act. Uncertainty about baseline, severity, or',
  'the package bump is a signal to stop and ask, not to guess.',
  '',
].join('\n');
