import { execFile } from 'node:child_process';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { promisify } from 'node:util';
import { expect, test } from 'vitest';
import { bin, exampleFixture } from './e2e-fixture';

const run = promisify(execFile);
const fixture = () => exampleFixture('vtk-ramp-', 'extensions');

test('a virtual ramp exports, refuses edits, commits via ramp build, and --check guards it', async () => {
  const cwd = await fixture();

  // Virtual: generated stops reach the css output; the anchor step is the brand hex verbatim.
  await run('node', [bin, 'build'], { cwd });
  const css = await readFile(join(cwd, 'build/css/tokens.css'), 'utf8');
  expect(css).toMatch(/--color-teal-100: oklch/);
  expect(css).toMatch(/--color-teal-300: oklch\(0\.6884 0\.1148 188\.2\)/);

  // Generated tokens are views — the verbs say where the truth lives.
  const refused = await run(
    'node',
    [bin, 'token', 'set', 'color.teal.200', '#ff0000'],
    { cwd },
  ).catch((e: { code: number; stderr: string }) => e);
  expect(refused.code).toBe(1);
  expect(refused.stderr).toContain('generated by');

  // Committed: the stops become real tokens; the payload stays the source.
  await run('node', [bin, 'ramp', 'build'], { cwd });
  const core = JSON.parse(
    await readFile(join(cwd, 'tokens/core.json'), 'utf8'),
  );
  expect(core.color.teal['300'].$value.hex).toBe('#1DB1A8');
  expect(
    Object.keys(core.color.teal).filter((k) => !k.startsWith('$')),
  ).toHaveLength(5);
  const check = await run('node', [bin, 'check', '--json'], { cwd });
  expect(JSON.parse(check.stdout).ok).toBe(true);

  // Fresh; then a hand-edited stop is stale.
  const fresh = await run('node', [bin, 'ramp', 'build', '--check'], { cwd });
  expect(fresh.stdout).toContain('1 committed ramp(s) fresh');
  core.color.teal['500'].$value.hex = '#000000';
  const { writeFile } = await import('node:fs/promises');
  await writeFile(join(cwd, 'tokens/core.json'), JSON.stringify(core, null, 2));
  const stale = await run('node', [bin, 'ramp', 'build', '--check'], {
    cwd,
  }).catch((e: { code: number; stderr: string }) => e);
  expect(stale.code).toBe(1);
  expect(stale.stderr).toContain('stale ramp stop(s): color.teal.500');
}, 120_000);

test('an unresolvable anchor is loud in check', async () => {
  const cwd = await fixture();
  const corePath = join(cwd, 'tokens/core.json');
  const core = JSON.parse(await readFile(corePath, 'utf8'));
  core.color.teal.$extensions['org.vertekum.generate/ramp'].anchor =
    '{brand.nope}';
  const { writeFile } = await import('node:fs/promises');
  await writeFile(corePath, JSON.stringify(core, null, 2));

  const refused = await run('node', [bin, 'check', '--json'], { cwd }).catch(
    (e: { code: number; stdout: string }) => e,
  );
  expect(refused.code).toBe(1);
  const report = JSON.parse(refused.stdout);
  expect(
    report.diagnostics.some(
      (d: { code: string }) => d.code === 'ramp/unresolved-anchor',
    ),
  ).toBe(true);
}, 60_000);

test('sets live in subdirectories: read, created by verb, removed with their dir', async () => {
  const cwd = await fixture();

  // The shipped nested set is read and exported like any other.
  const described = await run('node', [bin, 'describe', '--json'], { cwd });
  expect(JSON.parse(described.stdout).project.sets).toContain('brands/print');

  await run('node', [bin, 'set', 'add', 'brands/extra'], { cwd });
  await run(
    'node',
    [
      bin,
      'token',
      'add',
      'x.y',
      '4px',
      '--type',
      'dimension',
      '--set',
      'brands/extra',
    ],
    { cwd },
  );
  const file = join(cwd, 'tokens/brands/extra.json');
  expect(JSON.parse(await readFile(file, 'utf8')).x.y.$value).toEqual({
    value: 4,
    unit: 'px',
  });

  await run('node', [bin, 'set', 'remove', 'brands/extra', '--force'], { cwd });
  const check = await run('node', [bin, 'check', '--json'], { cwd });
  expect(JSON.parse(check.stdout).ok).toBe(true);
}, 120_000);
