import type { Token } from './types';

/**
 * Extension-held token data (designed in dialogue, 2026-08-26).
 *
 * A custom-typed token — one no DTCG `$type` can carry — is STORED as a node whose only member is
 * `$extensions`: to every conformant tool that is an empty group, and `$extensions` is the one
 * channel the spec obligates tools to preserve. The file stays 100% conformant DTCG; the dialect
 * lives entirely in the payload under a vendor key the owning extension chooses.
 *
 * A codec is that extension's read/write mechanics, registered into the kernel: `materialize`
 * turns the stored payload into an ordinary token in the in-memory model (so aliasing, resolution,
 * verbs, exporters, and the UI see nothing special), and `serialize` is the inverse the document's
 * write path calls to keep the store conformant. Custom types are the first tenant; anything an
 * extension holds as token-shaped data (ramp definitions, scale builders…) rides the same seam.
 */
/** The fields a codec yields for one token — the model fills in identity and provenance. */
export interface CodecTokenFields {
  type: string;
  value: unknown;
  description?: string;
}

/** What a group codec's `expand` can see beyond its own payload. */
export interface GroupCodecContext {
  /**
   * Follow alias chains (`"{brand.accent}"`) against the parsed collection to the
   * effective value; a non-reference passes through; undefined when the chain dangles or
   * cycles. Resolution sees ordinary and value-codec tokens — a token generated by another
   * group is not addressable from here.
   */
  resolve(value: unknown): unknown;
}

/** A value codec: one carrier node ⇄ one token. */
export interface ValueTokenCodec {
  /** The `$extensions` key this codec owns. Unique — registering a duplicate throws. */
  key: string;
  /**
   * Stored payload → token fields, or null to leave the node a plain group. The codec owns its
   * payload's shape entirely; core never interprets it.
   */
  materialize(
    payload: unknown,
    at: { set: string; path: string[] },
  ): CodecTokenFields | null;
  /**
   * The inverse: the payload to store for this token. A derivation codec — one whose payload is a
   * formula rather than the value itself — reads `token.codecSource` (the payload as parsed,
   * carried with the token) for the parts a computed value cannot reproduce.
   */
  serialize(token: Token): unknown;
}

/**
 * A group codec: one carrier group → MANY generated child tokens (a colour ramp from an anchor,
 * a scale from a formula). The carrier rule is unchanged — a LEAF group carrying the key — which
 * is also what lets virtual and committed modes coexist without a flag: a group holding real
 * children never expands, so its payload is inert data a build command reads.
 *
 * Generated tokens are views, not storage: they carry `generated: true`, the curation verbs
 * refuse to mutate them, and the store never writes them — the payload is the single source.
 */
export interface GroupTokenCodec {
  /** The `$extensions` key this codec owns. Unique — registering a duplicate throws. */
  key: string;
  /**
   * Payload → generated children (name → fields), or null to leave the group plain (an
   * unresolvable anchor, a malformed payload — the extension's schema or validator says why).
   */
  expand(
    payload: unknown,
    at: { set: string; path: string[] },
    ctx: GroupCodecContext,
  ): Record<string, CodecTokenFields> | null;
}

export type TokenCodec = ValueTokenCodec | GroupTokenCodec;

/** Discriminant: group codecs expand; value codecs materialize/serialize. */
export function isGroupCodec(codec: TokenCodec): codec is GroupTokenCodec {
  return 'expand' in codec;
}

export interface TokenCodecService {
  register(codec: TokenCodec): void;
  get(key: string): TokenCodec | undefined;
  list(): TokenCodec[];
  /** Notifies on registration — the document invalidates its derived views through this. */
  subscribe(listener: () => void): () => void;
}

/** The well-known service key extensions reach the registry under (`ctx.services.get(...)`). */
export const TOKEN_CODEC_SERVICE = 'token-codec';

/** The kernel pre-creates this — core itself consumes codecs, unlike purely-contributed services. */
export function createTokenCodecRegistry(): TokenCodecService {
  const byKey = new Map<string, TokenCodec>();
  const listeners = new Set<() => void>();
  let snapshot: TokenCodec[] | null = null;
  return {
    register(codec) {
      if (byKey.has(codec.key)) {
        throw new Error(
          `a token codec for '${codec.key}' is already registered — one extension owns a key`,
        );
      }
      byKey.set(codec.key, codec);
      snapshot = null;
      for (const listener of listeners) listener();
    },
    get(key) {
      return byKey.get(key);
    },
    list() {
      if (snapshot === null) snapshot = [...byKey.values()];
      return snapshot;
    },
    subscribe(listener) {
      listeners.add(listener);
      return () => {
        listeners.delete(listener);
      };
    },
  };
}
